# first 8 char of the SHA commit : CI_COMMIT_SHORT_SHA
# name of the targetted branch of the MR : CI_MERGE_REQUEST_TARGET_BRANCH_NAME

stages:
  - build-frontend
  - build-backend
  - sonar


variables:
  GRADLE_OPTS: "-Dhttp.proxyHost=192.168.4.8 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=192.168.4.8 -Dhttps.proxyPort=3128 -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  ORG_GRADLE_JVM_ARGS: "-Xmx1024m -XX:MaxPermSize=256m"
  ## Value of variables in gitlab>ci_cd>variables
  # DEV_SERVER_IP: ""     
  # PROD_SERVER_IP: ""    
  # $SSH_USER
  # SSH_PRIVATE_KEY_DEV
  # SSH_PRIVATE_KEY_PROD

before_script:
  - export https_proxy=http://192.168.4.8:3128/
  - export http_proxy=http://192.168.4.8:3128/




########################
## BUILD frontend DEV ##
########################
vuejs-build-dev:
  stage: build-frontend
  image: node:16.19.1-alpine3.17
  script:
    - cd frontend
    - npm install --legacy-peer-deps
    - npm run build-only:dev
  retry: 2
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hrs
  cache:
    paths:
      - frontend/node_modules
  only:
    - dev
    - gitlab-ci


#########################
## BUILD frontend PROD ##
#########################
vuejs-build-prod:
  stage: build-frontend
  image: node:16.19.1-alpine3.17
  script:
    - cd frontend
    - npm install --legacy-peer-deps
    - npm run build-only:prod
  retry: 2
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hrs
  cache:
    paths:
      - frontend/node_modules
  only:
    - main


###############################
## BUILD backend DEV or PROD ##
###############################
java-build:
  stage: build-backend
  image: gradle:8.4-jdk17
  script:
    - cd backend
    - mkdir -p src/main/resources/static
    - cp -r ../frontend/dist/* src/main/resources/static/
    - gradle --no-daemon clean build -Pdev -x test
  retry: 2
  dependencies:    
    - vuejs-build-dev
    - vuejs-build-prod
  cache:
    paths:
      - $CI_PROJECT_DIR/.gradle/caches
  artifacts:
    paths:
      - backend/build/libs/*.war
    expire_in: 5 days
    when: always


###########
## SONAR ##
###########
quality-dev:
  stage: sonar
  image: gradle:8.4-jdk17
  script:
    - cd backend
    - chmod +x ./gradlew
    - ./gradlew --no-daemon test 
    - ./gradlew --no-daemon sonar -Dsonar.projectKey=Team4_2024_DevBranch_Project -Dsonar.host.url=http://172.24.1.1:9000/sonar -Dsonar.login=c5b2dd816af047dc15120ef5b683457c0a5a128c -Dsonar.java.binaries=build/classes/java/main
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/libs/*.war
    expire_in: 1 day
    when: always
  retry: 2
  dependencies:
    - java-build
  cache:
    paths:
      - $CI_PROJECT_DIR/.gradle/caches
  only:
    - dev
    - gitlab-ci

quality-prod:
  stage: sonar
  image: gradle:8.4-jdk17
  script:
    - cd backend
    - chmod +x ./gradlew
    - ./gradlew --no-daemon test
    - ./gradlew --no-daemon sonar -Dsonar.projectKey=Team4_2024_MasterBranch_Project -Dsonar.host.url=http://172.24.1.1:9000/sonar -Dsonar.login=50173e34bc59d1e7554c1d9a3cdf0e511a87b457 -Dsonar.java.binaries=build/classes/java/main
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/libs/*.war
    expire_in: 1 day
    when: always
  retry: 2
  dependencies:
    - java-build
  cache:
    paths:
      - $CI_PROJECT_DIR/.gradle/caches
  only:
    - main







