# first 8 char of the SHA commit : CI_COMMIT_SHORT_SHA
# name of the targetted branch of the MR : CI_MERGE_REQUEST_TARGET_BRANCH_NAME

stages:
  - build
  - sonar
  - deploy-server-dev
  - deploy-server-prod

variables:
  GRADLE_OPTS: "-Dhttp.proxyHost=192.168.4.8 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=192.168.4.8 -Dhttps.proxyPort=3128 -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  ORG_GRADLE_JVM_ARGS: "-Xmx1024m -XX:MaxPermSize=256m"
  ## Value of variables in gitlab>ci_cd>variables
  # DEV_SERVER_IP: ""     
  # PROD_SERVER_IP: ""    
  # $SSH_USER
  # SSH_PRIVATE_KEY_DEV
  # SSH_PRIVATE_KEY_PROD

before_script:
  - export https_proxy=http://192.168.4.8:3128/
  - export http_proxy=http://192.168.4.8:3128/



###########
## BUILD ##
###########       
vuejs-build:
  stage: build
  image: node:16.19.1-alpine3.17
  script:
    - cd frontend
    - npm install --legacy-peer-deps
    - npm run build-only:dev
  retry: 2
  cache:
    paths:
      - frontend/node_modules
 
java-build:
  stage: build
  image: gradle:8.4-jdk17
  script:
    - cd backend
    - gradle --no-daemon clean build -x test
  artifacts:
    name: "Gradle artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - $CI_PROJECT_DIR/build/libs/*.war
      - backend/build/classes/
    expire_in: 1 day
    when: always
  retry: 2
  cache:
    paths:
      - $CI_PROJECT_DIR/.gradle/caches
  dependencies:     # Set accessible data in vuejs-build, to copy data from frontend folder 
    - vuejs-build



###########
## SONAR ##
###########
quality-dev:
  stage: sonar
  image: gradle:8.4-jdk17
  script:
    - cd backend
    - chmod +x ./gradlew
    - ./gradlew --no-daemon test  # Use temp DB in backend in application-test.properties (h2)
    - ./gradlew --no-daemon sonar -Dsonar.projectKey=Team4_2024_DevBranch_Project -Dsonar.host.url=http://172.24.1.1:9000/sonar -Dsonar.login=c5b2dd816af047dc15120ef5b683457c0a5a128c -Dsonar.java.binaries=build/classes/java/main
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/libs/*.war
    expire_in: 1 day
    when: always
  retry: 2
  dependencies:
    - java-build
  cache:
    paths:
      - $CI_PROJECT_DIR/.gradle/caches
  only:
    - dev
    - gitlab-ci

quality-prod:
  stage: sonar
  image: gradle:8.4-jdk17
  script:
    - cd backend
    - chmod +x ./gradlew
    - ./gradlew --no-daemon test  # Use temp DB in backend in application-test.properties (h2)
    - ./gradlew --no-daemon sonar -Dsonar.projectKey=Team4_2024_MasterBranch_Project -Dsonar.host.url=http://172.24.1.1:9000/sonar -Dsonar.login=50173e34bc59d1e7554c1d9a3cdf0e511a87b457 -Dsonar.java.binaries=build/classes/java/main
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/libs/*.war
    expire_in: 1 day
    when: always
  retry: 2
  dependencies:
    - java-build
  cache:
    paths:
      - $CI_PROJECT_DIR/.gradle/caches
  only:
    - main



################
## Deploy dev ##
################
vuejs-deploy-dev:
  stage: deploy-server-dev
  image: node:16.19.1-alpine3.17
  script:
    - cd frontend
    - npm install --legacy-peer-deps
    - npm run build-only:dev
  retry: 2
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hrs
  cache:
    paths:
      - frontend/node_modules
  only:
    - dev
    - gitlab-ci

java-deploy-dev:
  stage: deploy-server-dev
  image: gradle:8.4-jdk17
  script:
    - cd backend
    - gradle --no-daemon clean build -Pdev -x test
  retry: 2
  dependencies:     # Set accessible data in vuejs-deploy-dev, to copy data from frontend folder 
    - vuejs-deploy-dev
  cache:
    paths:
      - $CI_PROJECT_DIR/.gradle/caches
  artifacts:
    paths:
      - backend/build/libs/*.war
    expire_in: 5 days
    when: always
  only:
    - dev
    - gitlab-ci

push-deploy-dev:
  stage: deploy-server-dev
  image: docker push charlo56/pgl-ssh-image:latest
  dependencies:
    - java-deploy-dev   # Start after vuejs-deploy-dev is ready
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_DEV" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEV_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - mv backend/build/libs/*plain.war backend/build/libs/tauri.war
    - scp -o StrictHostKeyChecking=no backend/build/libs/tauri.war $SSH_USER@$DEV_SERVER_IP:/srv/tomcat/webapps 
  retry: 2



#################
## Deploy prod ##
#################
vuejs-deploy-prod:
  stage: deploy-server-prod
  image: node:16.19.1-alpine3.17
  script:
    - cd frontend
    - npm install --legacy-peer-deps
    - npm run build-only:prod
  retry: 2
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hrs
  cache:
    paths:
      - frontend/node_modules
  only:
    - main

java-deploy-prod:
  stage: deploy-server-prod
  image: gradle:8.4-jdk17
  script:
    # - cp -r ./frontend/dist ./backend/src/main/resources/static
    - cd backend
    - gradle --no-daemon clean build -Pprod -x test
  dependencies:     # Set accessible data in vuejs-deploy-prod, to copy data from frontend folder 
    - vuejs-deploy-prod
  cache:
    paths:
      - $CI_PROJECT_DIR/.gradle/caches
  artifacts:
    paths:
      - backend/build/libs/*.war
    expire_in: 5 days
    when: always
  only:
    - main