<script setup lang="ts">

import { Column } from "@/components/atoms/containers"

const emitAdd = defineEmits(["add:sprint"])




</script>

<template>
    <div class="border border-gray-300 border-dashed rounded-lg hover:bg-gray-100 flex justify-center flex-col items-stretch">
            <Column class="items-center py-4 gap-2">
                ajoute tes users ic 
            </Column>
    </div>
</template>